#POST https://example.com/comments HTTP/1.1
#content-type: application/json


POST http://localhost:7118/api/StartTranslation HTTP/1.1
preprocess_url: https://povelfstorage.blob.core.windows.net/preprocessed/en-content-01.txt
translated_url: https://povelfstorage.blob.core.windows.net/translated/sv-content-01.txt